const books = [
  {
    id: "1",
    slug: "the-silent-library",
    title: "The Silent Library",
    author: "Emma Carter",
    price: 19.99,
    description: "A mystery novel about a forgotten library hiding secrets that could change history.",
    coverImageUrl: "https://picsum.photos/seed/book1/400/600",
    category: "Mystery",
    createdAt: "2026-01-15T10:30:00Z",
    rating: 4.6,
    ratingsCount: 124,
    stock: 45,
    pages: 352,
    publisher: "North Star Press",
    language: "English",
    isbn: "9781234567891"
  },
  {
    id: "2",
    slug: "echoes-of-tomorrow",
    title: "Echoes of Tomorrow",
    author: "Liam Brooks",
    price: 24.5,
    description: "A gripping science fiction adventure exploring time travel and its consequences.",
    coverImageUrl: "https://picsum.photos/seed/book2/400/600",
    category: "Science Fiction",
    createdAt: "2026-02-03T08:45:00Z",
    rating: 4.8,
    ratingsCount: 312,
    stock: 28,
    pages: 416,
    publisher: "Future Ink",
    language: "English",
    isbn: "9781234567892"
  },
  {
    id: "3",
    slug: "mountains-beyond-clouds",
    title: "Mountains Beyond Clouds",
    author: "Sophia Reed",
    price: 17.99,
    description: "An inspiring journey of self-discovery through remote mountain villages.",
    coverImageUrl: "https://picsum.photos/seed/book3/400/600",
    category: "Adventure",
    createdAt: "2026-02-21T14:10:00Z",
    rating: 4.3,
    ratingsCount: 89,
    stock: 67,
    pages: 288,
    publisher: "Summit House",
    language: "English",
    isbn: "9781234567893"
  },

  // ... Books 4–47 omitted for brevity ...

  {
    id: "48",
    slug: "the-golden-compass",
    title: "The Golden Compass",
    author: "Nathan Price",
    price: 18.99,
    description: "A historical adventure spanning continents and generations.",
    coverImageUrl: "https://picsum.photos/seed/book48/400/600",
    category: "History",
    createdAt: "2026-05-12T11:00:00Z",
    rating: 4.5,
    ratingsCount: 187,
    stock: 32,
    pages: 378,
    publisher: "Legacy Books",
    language: "English",
    isbn: "9781234567938"
  },
  {
    id: "49",
    slug: "the-last-expedition",
    title: "The Last Expedition",
    author: "Amelia Stone",
    price: 23.99,
    description: "An expedition into uncharted territory reveals unexpected truths.",
    coverImageUrl: "https://picsum.photos/seed/book49/400/600",
    category: "Adventure",
    createdAt: "2026-05-18T13:15:00Z",
    rating: 4.7,
    ratingsCount: 296,
    stock: 21,
    pages: 442,
    publisher: "Explorer Press",
    language: "English",
    isbn: "9781234567939"
  },
  {
    id: "50",
    slug: "future-foundations",
    title: "Future Foundations",
    author: "Daniel King",
    price: 29.99,
    description: "A practical guide to technology, innovation, and leadership.",
    coverImageUrl: "https://picsum.photos/seed/book50/400/600",
    category: "Business",
    createdAt: "2026-05-25T09:30:00Z",
    rating: 4.9,
    ratingsCount: 512,
    stock: 15,
    pages: 520,
    publisher: "Visionary Publishing",
    language: "English",
    isbn: "9781234567940"
  }
];